In [1]:
import pandas as pd
import numpy as np
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows as df_to_row

In [2]:
from szp_funcs import create_res, print_df, path_to_data, load_groups, get_otv, get_fio

In [3]:
ped, isp, aup = load_groups('input')
months = ['apr']

In [4]:
otv = get_otv()

In [5]:
fio = get_fio()

In [6]:
res = create_res(months)

In [29]:
min_teach = res[res['job_' + months[0]] == 'Учитель'][['inn', 'snils', 'sum_' + months[0], 'job_' + months[0], 'stv_' + months[0]]].groupby('snils').max().reset_index()
min_teach = min_teach[min_teach['sum_' + months[0]] < 84100]

In [30]:
min_nped = res[res['job_' + months[0]].isin(ped) == False][['inn', 'snils', 'sum_' + months[0], 'job_' + months[0], 'stv_' + months[0]]].groupby('snils').max().reset_index()
min_nped = min_nped[min_nped['sum_' + months[0]] < 54500]

In [9]:
donach = pd.read_excel(path_to_data + 'early_may' + '.xlsx')

In [27]:
donach = donach.groupby(['inn', 'snils']).sum().reset_index()

In [28]:
donach

              inn           snils        sum
0      5003021368  001-191-281 85   10000.00
1      5003021368  001-244-107 65   10000.00
2      5003021368  001-519-663 10   10000.00
3      5003021368  002-562-177 05   10000.00
4      5003021368  003-558-539 37   10000.00
...           ...             ...        ...
61005  9718071371  156-724-841 91  229026.14
61006  9718071371  160-296-736 70    8721.96
61007  9718071371  162-043-658 38  234000.00
61008  9718071371  165-092-321 58   35784.35
61009  9718071371  193-646-863 19   27380.15

[61010 rows x 3 columns]

In [31]:
min_nped = pd.merge(min_nped, donach, on=['snils', 'inn'], how='left')
min_nped['sum_' + months[0]] = min_nped.sum_apr + min_nped['sum']
min_nped = min_nped[min_nped['sum_' + months[0]] < 54500][['inn', 'snils', 'sum_' + months[0], 'job_' + months[0], 'stv_' + months[0]]]

In [44]:
min_nped

             inn           snils   sum_apr
10    7728007477  001-240-239 60  47845.84
28    7735096830  001-459-582 24  38202.08
38    7723881258  001-612-359 84  49718.09
67    7728229430  001-897-360 48  47839.08
90    7728229430  003-041-761 79  53096.12
144   7720325492  007-098-313 39  42919.28
239   7728229430  015-543-224 18  42582.05
272   7721223373  017-153-103 05  41081.91
276   7731173700  017-429-028 38  53006.54
286   7733148875  018-160-587 37  29542.86
291   7743021236  018-339-961 72  42046.44
292   7743021236  018-339-961 72  40435.72
408   7731174051  023-584-486 56  50805.11
414   7727506385  023-933-501 33  32323.42
455   7731173523  025-520-387 22  53340.34
466   5074045703  025-844-669 73  47989.48
474   7709330442  025-965-457 83  27175.22
483   7719286023  026-104-843 14  45171.91
584   7713039050  042-100-319 72  45371.16
610   5030032376  047-316-089 52  47815.60
625   7725539709  050-216-405 98  44150.46
685   7725144330  057-356-873 96  44867.63
709   7728229430  062-385-325 57  51422.83
713   7728229430  062-730-875 61  37325.00
770   7728900440  070-419-563 50  53161.18
779   7723327297  071-404-678 42  47825.71
860   7728007477  080-244-826 45  50906.67
944   7728229430  107-293-857 67  47794.33
960   7729400426  108-843-364 69  47684.82
1075  7728007477  118-634-429 64  44802.25
1086  7729783137  119-641-052 51  34653.58
1177  7732507722  126-475-034 55  51664.49
1185  7715982037  126-975-651 03  54381.85
1264  7725247657  132-635-830 47  48190.47
1350  7733853690  137-850-827 89  21588.68
1354  7705480398  138-033-646 47  36826.67
1368  7724731696  138-908-091 93  52553.58
1378  7728229430  139-280-966 92  42582.05
1387  7727213822  139-946-245 11  38928.56
1453  7716199407  145-015-575 34  46305.98
1500  7724859424  148-668-327 13  46627.71
1613  7731173820  156-822-450 78  36276.16
1667  7727844923  163-236-757 66  38397.48
1841  7737078033  195-945-941 44   3546.09
1849  7723305800  198-610-244 95  46714.29

In [32]:
min_nped_out = pd.merge(pd.merge(min_nped, fio, on='snils', how='left'), otv, how='left', on='inn')

In [18]:
min_nped_out

,inn,snils,sum_apr,job_apr,stv_apr,fio,okr,otv,sch_name
0,7728007477,001-240-239 60,47845.84,Помощник воспитателя,1.0,Лендел Екатерина Ивановна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1101
1,7735096830,001-459-582 24,38202.08,Помощник воспитателя,1.0,Князева Надежда Николаевна,ЗелАО,Майильян Елена Александровна,ГБОУ Школа № 1150
2,7723881258,001-612-359 84,49718.09,Рабочий по комплексному обслуживанию и ремонту...,1.0,Павлова Ольга Николаевна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 491
3,7728229430,001-897-360 48,47839.08,Помощник воспитателя,1.0,Короткова Виктория Александровна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
4,7728229430,003-041-761 79,53096.12,Помощник воспитателя,1.0,Лактюшина Светлана Геннадьевна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
5,7720325492,007-098-313 39,42919.28,Специалист по охране труда,1.0,Чиненова Марина Анатольевна,ВАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 2127
6,7728229430,015-543-224 18,42582.05,Помощник воспитателя,1.0,Шатухо Елена Николаевна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
7,7721223373,017-153-103 05,41081.91,Помощник воспитателя,1.0,Михайлова Оксана Викторовна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 777
8,7731173700,017-429-028 38,53006.54,Помощник воспитателя,1.0,Филина Елена Александровна,ЗАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 887
9,7733148875,018-160-587 37,29542.86,Помощник воспитателя,1.0,Лебедева Наталья Александровна,СЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1538
10,7743021236,018-339-961 72,42046.44,Помощник воспитателя,1.0,Лапина Лариса Сергеевна,САО,Рагимова Виктория Олеговна,"ГБОУ ""Школа № 597 ""Новое Поколение"""
11,7743021236,018-339-961 72,40435.72,Помощник воспитателя,1.0,Лапина Лариса Сергеевна,САО,Рагимова Виктория Олеговна,"ГБОУ ""Школа № 597 ""Новое Поколение"""
12,7731174051,023-584-486 56,50805.11,Помощник воспитателя,1.0,Хромова Наталия Валерьевна,ЗАО,Шехмуратова Евгения Евгеньевна,"ГБОУ Школа № 1371 ""Крылатское"""
13,7727506385,023-933-501 33,32323.42,Рабочий по комплексному обслуживанию и ремонту...,1.0,Куватов Дамир Закирьянович,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 2009
14,7731173523,025-520-387 22,53340.34,Помощник воспитателя,1.0,Суровикина Татьяна Александровна,ЗАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 806
15,5074045703,025-844-669 73,47989.48,Помощник воспитателя,1.0,Квасова Елена Васильевна,ТиНАО,Горбанева Светлана Васильевна,ГБОУ Школа № 2083
16,7709330442,025-965-457 83,27175.22,Секретарь учебной части,1.0,Тихонова Татьяна Борисовна,ЦАО,Майильян Елена Александровна,ГБОУ Инженерная школа № 1581
17,7719286023,026-104-843 14,45171.91,Переводчик-дактилолог,1.0,Горшкова Эвелина Петровна,ВАО,Шехмуратова Евгения Евгеньевна,ГАПОУ ТК № 24
18,7713039050,042-100-319 72,45371.16,Помощник воспитателя,1.0,Осинина Олеся Алексеевна,САО,Рагимова Виктория Олеговна,ГБОУ Школа № 1576
19,5030032376,047-316-089 52,47815.60,Помощник воспитателя,1.0,Иванова Татьяна Васильевна,ТиНАО,Горбанева Светлана Васильевна,ГБОУ Школа № 1391
20,7725539709,050-216-405 98,44150.46,Специалист,1.0,Серова Ирина Сергеевна,ЮАО,Горбанева Светлана Васильевна,ГАОУ ДПО МЦКО
21,7725144330,057-356-873 96,44867.63,Рабочий по комплексному обслуживанию и ремонту...,1.0,Ховансков Дмитрий Александрович,ЮАО,Рагимова Виктория Олеговна,ГБОУ Школа № 1375
22,7728229430,062-385-325 57,51422.83,Помощник воспитателя,1.0,Герасимова Елена Сергеевна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
23,7728229430,062-730-875 61,37325.00,Помощник воспитателя,1.0,Томилина Виктория Николаевна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
24,7728900440,070-419-563 50,53161.18,Заведующий хозяйством,1.0,Комиссарова Елена Владимировна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1212
25,7723327297,071-404-678 42,47825.71,Помощник воспитателя,1.0,Малиновская Екатерина Сергеевна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 1547
26,7728007477,080-244-826 45,50906.67,Помощник воспитателя,1.0,Власкина Елена Владимировна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1101
27,7728229430,107-293-857 67,47794.33,Помощник воспитателя,1.0,Ермолова Наталья Вячеславовна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
28,7729400426,108-843-364 69,47684.82,Помощник воспитателя,1.0,Дунина Елена Герольдовна,ЗАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 1541
29,7728007477,118-634-429 64,44802.25,Помощник воспитателя,1.0,Луняк Светлана Юрьевна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1101
30,7729783137,119-641-052 51,34653.58,Ассистент по оказанию технической помощи,1.0,Смыкова Юлия Владимировна,ЗАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 1238
31,7732507722,126-475-034 55,51664.49,Секретарь учебной части,1.0,Алексеенко Елена Егоровна,ЗАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 1347
32,7715982037,126-975-651 03,54381.85,Помощник воспитателя,1.0,Казакова Елена Жаудатовна,СВАО,Горбанева Светлана Васильевна,ГБОУ Школа № 166
33,7725247657,132-635-830 47,48190.47,Плотник,1.0,Кузьмин Сергей Владимирович,ЮАО,Рагимова Виктория Олеговна,"ГБПОУ ОКГ ""Столица"""
34,7733853690,137-850-827 89,21588.68,Помощник воспитателя,1.0,Филимонова Анна Михайловна,СЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 883
35,7705480398,138-033-646 47,36826.67,Помощник воспитателя,1.0,Купцова Светлана Андреевна,ЦАО,Майильян Елена Александровна,ГБОУ Школа № 498
36,7724731696,138-908-091 93,52553.58,Помощник воспитателя,1.0,Ротова Светлана Михайловна,ЮАО,Рагимова Виктория Олеговна,ГБОУ Школа № 1579
37,7728229430,139-280-966 92,42582.05,Помощник воспитателя,1.0,Чуева Наталья Анатольевна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1532
38,7727213822,139-946-245 11,38928.56,Помощник воспитателя,1.0,Юхарева Анастасия Александровна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1980
39,7716199407,145-015-575 34,46305.98,Делопроизводитель,1.0,Калёнова Яна Алексеевна,СВАО,Горбанева Светлана Васильевна,ГБОУ Школа № 1955
40,7724859424,148-668-327 13,46627.71,Помощник воспитателя,1.0,Воробьева Наталья Владимировна,ЮАО,Рагимова Виктория Олеговна,ГБОУ Школа № 998
41,7731173820,156-822-450 78,36276.16,Помощник воспитателя,1.0,Воронина Светлана Александровна,ЗАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 1248
42,7727844923,163-236-757 66,38397.48,Помощник воспитателя,1.0,Геворгян Анна Гамлетовна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 2114
43,7737078033,195-945-941 44,3546.09,Вожатый,1.0,Алиева Эльмира Октайевна,ЮАО,Рагимова Виктория Олеговна,ГБОУ Школа № 1207
44,7723305800,198-610-244 95,46714.29,Помощник воспитателя,1.0,Булбуланц Нона Бениковна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 1524

In [33]:
print_df(min_nped_out, '54,5-' + months[0])

In [34]:
min_teach = pd.merge(min_teach, donach, on=['snils', 'inn'], how='left')
min_teach['sum_' + months[0]] = min_teach.sum_apr + min_teach['sum']
min_teach = min_teach[min_teach['sum_' + months[0]] < 84100][['inn', 'snils', 'sum_' + months[0], 'job_' + months[0], 'stv_' + months[0]]]

In [35]:
min_teach[min_teach.duplicated(['inn', 'snils']) == True]

Empty DataFrame
Columns: [inn, snils, sum_apr, job_apr, stv_apr]
Index: []

In [21]:
min_teach.drop_duplicates(['inn', 'snils'])

             inn           snils   sum_apr  job_apr  stv_apr
0     7718309983  001-005-786 70  82633.85  Учитель     1.00
1     7713782829  001-109-381 75  80946.54  Учитель     1.00
3     7719025840  001-142-500 56  62068.02  Учитель     1.00
12    7727506385  001-192-096 90  73186.34  Учитель     1.00
15    7735062743  001-200-424 39  57668.16  Учитель     1.00
...          ...             ...       ...      ...      ...
3978  7733126624  210-523-311 90  83002.85  Учитель     1.00
3979  7713288810  210-789-096 67  82931.63  Учитель     1.28
3981  7721816905  212-319-648 32  61438.18  Учитель     1.00
3982  7721223373  212-319-673 33  77726.86  Учитель     1.00
3984  7721804748  212-640-497 32  80959.48  Учитель     1.00

[1539 rows x 5 columns]

In [36]:
min_teach_out = pd.merge(pd.merge(min_teach, fio, on='snils', how='left').drop_duplicates(['inn', 'snils']), otv, how='left', on='inn')

In [37]:
min_teach_out

,inn,snils,sum_apr,job_apr,stv_apr,fio,okr,otv,sch_name
0,7718309983,001-005-786 70,82633.85,Учитель,1.00,Тушина Наталия Юрьевна,ВАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 1797
1,7713782829,001-109-381 75,80946.54,Учитель,1.00,Бакунина Татьяна Викторовна,САО,Рагимова Виктория Олеговна,"ГБОУ Школа № 1454 ""Тимирязевская"""
2,7719025840,001-142-500 56,62068.02,Учитель,1.00,Потапова Ольга Валерьевна,ВАО,Шехмуратова Евгения Евгеньевна,ГБОУ Школа № 1508
3,7727506385,001-192-096 90,73186.34,Учитель,1.00,Сыкчина Ирина Альбертовна,ЮЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 2009
4,7735062743,001-200-424 39,57668.16,Учитель,1.00,Новик Валентина Ивановна,ЗелАО,Майильян Елена Александровна,ГБОУ Школа № 1528
...,...,...,...,...,...,...,...,...,...
1522,7733126624,210-523-311 90,83002.85,Учитель,1.00,Романова Юлия Викторовна,СЗАО,Застаева Таисия Саналовна,ГБОУ Школа № 1571
1523,7713288810,210-789-096 67,82931.63,Учитель,1.28,Садовникова Анастасия Сергеевна,САО,Рагимова Виктория Олеговна,ГБОУ Школа № 1213
1524,7721816905,212-319-648 32,61438.18,Учитель,1.00,Лищинская Оксана Михайловна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 1208
1525,7721223373,212-319-673 33,77726.86,Учитель,1.00,Рогожина Ирина Дмитриевна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 777
1526,7721804748,212-640-497 32,80959.48,Учитель,1.00,Акчурина Ольга Олеговна,ЮВАО,Майильян Елена Александровна,ГБОУ Школа № 2090

In [38]:
print_df(min_teach_out, '84,1-' + months[0])