In [37]:
from fuzzywuzzy import process, fuzz
import pandas as pd
import numpy as np

In [38]:
from szp_funcs import  print_df, path_to_data, matcher

In [39]:
path_to_dir = 'C:/Users/PetukhovMD/Desktop/Направления и категории/'
file = 'новые данные в выгрузках.xlsx'
pages = ['job_cat', 'job_direc', 'source']

In [40]:
source = pd.read_excel(path_to_dir + file, sheet_name=pages[2])
res = pd.read_excel(path_to_data + 'jun.xlsx')
inn = [7736212529]

In [41]:
res.columns

Index(['inn', 'snils', 'type', 'stv', 'status', 'sum_all', 'status_pref',
       'wday', 'nday', 'spec', 'sum', 'day', 'job'],
      dtype='object')

In [42]:
source

,job,type,direc
0,Главный бухгалтер,Административно-управленческий персонал,NaN
1,Директор,Административно-управленческий персонал,NaN
2,Директор филиала,Административно-управленческий персонал,NaN
3,Заведующий,Административно-управленческий персонал,NaN
4,Заместитель главного бухгалтера,Административно-управленческий персонал,NaN
...,...,...,...
454,Старший инженер по ремонту,Прочий персонал (включая иной административный...,NaN
455,Специалист по гражданской обороне и защите в ч...,Прочий персонал (включая иной административный...,NaN
456,Электромонтер по ремонту и обслуживанию электр...,Прочий персонал (включая иной административный...,NaN
457,Ведущий юрисконсульт,Прочий персонал (включая иной административный...,NaN
458,Старший юрисконсульт,Прочий персонал (включая иной административный...,NaN

In [43]:
jobs_source = source['job'].unique().tolist()

In [44]:
jobs_res = res[res.inn.isin(inn)][['snils', 'job', 'spec']].drop_duplicates().rename(columns={'job': 'job_pre', 'spec': 'direc'})

In [45]:
jobs_res['job'] = jobs_res.apply(lambda row: matcher(row, jobs_source, 'job_pre'), axis=1)

In [46]:
ans = pd.merge(jobs_res, source, how='left', on=['job', 'direc'])

In [54]:
ans[ans.type.isna()]['snils'].unique().tolist()

['001-183-402 79',
 '001-577-540 22',
 '001-792-990 46',
 '009-096-458 61',
 '010-749-581 37',
 '017-696-281 84',
 '018-344-658 53',
 '019-705-301 42',
 '020-800-958 08',
 '028-449-164 70',
 '029-237-290 57',
 '034-076-655 43',
 '039-355-143 63',
 '048-739-582 12',
 '070-933-549 68',
 '073-969-918 32',
 '074-420-399 53',
 '128-215-483 48',
 '129-106-076 37',
 '132-089-944 61',
 '132-931-865 60',
 '137-485-661 96',
 '141-844-825 64',
 '148-662-250 86',
 '157-239-261 79',
 '159-186-109 93',
 '162-261-634 44',
 '166-195-497 05',
 '167-895-429 42',
 '168-398-818 40',
 '186-092-411 82',
 '189-823-478 38']

In [55]:
len(ans[ans.type.isna()]['snils'].unique().tolist())

32

In [48]:
source[source.job == 'Специалист']

,job,type,direc
369,Специалист,Прочий персонал (включая иной административный...,в сфере ИКТ
370,Специалист,Прочий персонал (включая иной административный...,по здоровьесбережению и профилактике травматизма
371,Специалист,Прочий персонал (включая иной административный...,по инклюзивному образованию
372,Специалист,Прочий персонал (включая иной административный...,по комплексной безопасности
373,Специалист,Прочий персонал (включая иной административный...,по материально-техническому обеспечению
374,Специалист,Прочий персонал (включая иной административный...,по музейной работе
375,Специалист,Прочий персонал (включая иной административный...,по обслуживанию инженерных систем
376,Специалист,Прочий персонал (включая иной административный...,по питанию
377,Специалист,Прочий персонал (включая иной административный...,по пожарной безопасности
378,Специалист,Прочий персонал (включая иной административный...,по профессиональной подготовке
379,Специалист,Прочий персонал (включая иной административный...,по профилактике детского травматизма
380,Специалист,Прочий персонал (включая иной административный...,по профориентации
381,Специалист,Прочий персонал (включая иной административный...,по социальной работе
382,Специалист,Прочий персонал (включая иной административный...,по учету контингента
383,Специалист,Прочий персонал (включая иной административный...,приёмной комиссии
384,Специалист,Прочий персонал (включая иной административный...,учебной части
385,Специалист,Прочий персонал (включая иной административный...,по финансово-экономической деятельности
386,Специалист,Прочий персонал (включая иной административный...,NaN

In [49]:
jobs_res

,snils,job_pre,direc,job
39827,001-183-402 79,Заместитель директора,по контролю качества образования,Заместитель директора
39828,001-183-402 79,Учитель,NaN,Учитель
39829,001-440-074 69,Методист,NaN,Методист
39830,001-440-074 69,Учитель,математики,Учитель
39831,001-577-540 22,Педагог дополнительного образования,NaN,Педагог дополнительного образования
...,...,...,...,...
39939,186-092-411 82,Учитель,физика,Учитель
39940,187-886-574 65,Педагог-психолог,NaN,Педагог-психолог
39941,189-823-478 38,Учитель,NaN,Учитель
39942,195-849-578 55,Учитель,истории,Учитель
39943,214-738-388 75,Уборщик территории,NaN,Уборщик территории