In [1]:
from openpyxl import Workbook, load_workbook
import pandas as pd
import numpy as np

In [2]:
from szp_funcs import load_month, print_df

In [3]:
month = 'may'

In [4]:
res = load_month(month)

In [8]:
prep = res[['inn', 'snils', 'job_' + month]].rename(columns={'job_' + month: 'job'})

In [14]:
prep = prep.groupby(['inn', 'job']).nunique().unstack().reset_index()

In [18]:
prep.columns = [i[1] for i in prep.columns]

In [19]:
prep

,,Администратор,Администратор баз данных,Аккомпаниатор-концертмейстер,Аналитик,Архивариус,Ассистент,Ассистент по оказанию технической помощи,Балетмейстер,Библиотекарь,...,Эксперт,Электромеханик,Юрисконсульт,ведущий Аналитик,ведущий Бухгалтер,ведущий Документовед,специалист по технической документации в области информационных технологий,старший Администратор,старший Аналитик,старший Делопроизводитель
0,5003021368,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,5003021495,3.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5003021640,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5003096290,4.0,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
4,5030032182,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,7743940590,NaN,1.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,9705101759,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,9715206976,2.0,1.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
593,9715217689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,9718071371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,187.0,NaN,NaN,NaN,NaN,NaN

In [20]:
print_df(prep, 'Учреждения по должностям за ' + month)