In [1]:
import pandas as pd
import numpy as np
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows as df_to_row

In [37]:
from szp_funcs import path_to_data, to_double, print_df, get_otv

In [3]:
month = 'apr'

In [4]:
res = pd.read_excel(path_to_data + month + '.xlsx')

In [21]:
res['stv'] = res.apply(lambda row: to_double(row, 'stv'), axis=1)

In [5]:
stop = ['Увольнение']

In [14]:
a = res['job'].unique().tolist()
a.sort()
a

['no job value',
 'Администратор',
 'Администратор баз данных',
 'Аккомпаниатор-концертмейстер',
 'Аналитик',
 'Архивариус',
 'Ассистент',
 'Ассистент по оказанию технической помощи',
 'Балетмейстер',
 'Библиотекарь',
 'Бухгалтер',
 'Ведущий администратор баз данных',
 'Ведущий инженер-сметчик',
 'Ведущий научный сотрудник',
 'Ведущий программист',
 'Ведущий редактор',
 'Ведущий руководитель проектов',
 'Ведущий специалист',
 'Ведущий специалист по защите информации',
 'Ведущий специалист по кадрам',
 'Ведущий специалист по сетевому администрированию',
 'Ведущий экономист',
 'Ведущий юрисконсульт',
 'Видеооператор',
 'Водитель автомобиля',
 'Вожатый',
 'Воспитатель',
 'Гардеробщик',
 'Главный бухгалтер',
 'Главный научный сотрудник',
 'Главный редактор',
 'Главный специалист',
 'Главный художник',
 'Главный художник по свету',
 'Графический дизайнер',
 'Дежурный',
 'Дежурный по режиму',
 'Декан факультета',
 'Делопроизводитель',
 'Демонстратор пластических поз',
 'Дизайнер',
 'Директор',
 'Директор института',
 'Директор филиала',
 'Диспетчер образовательного учреждения',
 'Документовед',
 'Доцент',
 'Заведующий',
 'Заведующий библиотекой',
 'Заведующий кафедрой',
 'Заведующий костюмерной',
 'Заведующий лабораторией',
 'Заведующий отделением',
 'Заведующий практикой',
 'Заведующий производством',
 'Заведующий складом',
 'Заведующий учебной мастерской',
 'Заведующий учебной частью',
 'Заведующий хозяйством',
 'Закройщик',
 'Заместитель главного бухгалтера',
 'Заместитель директора',
 'Заместитель начальника',
 'Заместитель начальника - начальник управления',
 'Заместитель начальника отдела',
 'Заместитель начальника службы',
 'Заместитель начальника управления',
 'Заместитель руководителя',
 'Заместитель руководителя структурного подразделения',
 'Звукооператор',
 'Звукорежиссер',
 'Инженер по защите информации',
 'Инженер по звукозаписи',
 'Инженер-сметчик',
 'Инженер-тестировщик',
 'Инженер-электроник',
 'Инструктор по труду',
 'Инструктор по физической культуре',
 'Инструктор-методист',
 'Капитан',
 'Кастелянша',
 'Кинооператор',
 'Комендант',
 'Кондитер',
 'Консультант',
 'Консультант в области развития цифровой грамотности',
 'Контрактный управляющий',
 'Концертмейстер',
 'Корректор',
 'Корреспондент',
 'Лаборант',
 'Лаборант-исследователь',
 'Лифтер',
 'Мастер по ремонту',
 'Мастер производственного обучения',
 'Мастер производственной лаборатории',
 'Медицинская сестра',
 'Методист',
 'Механик',
 'Младший воспитатель',
 'Младший научный сотрудник',
 'Монтажер',
 'Монтировщик сцены',
 'Музыкальный руководитель',
 'Наладчик станков и манипуляторов с программным управлением',
 'Настройщик музыкальных инструментов',
 'Научный сотрудник',
 'Начальник',
 'Начальник группы',
 'Начальник отдела',
 'Начальник отдела кадров',
 'Начальник сектора',
 'Начальник службы',
 'Начальник управления',
 'Оператор видеозаписи',
 'Оператор котельной',
 'Осветитель',
 'Педагог дополнительного образования',
 'Педагог семейного детского сада',
 'Педагог-библиотекарь',
 'Педагог-организатор',
 'Педагог-психолог ',
 'Первый заместитель директора',
 'Первый заместитель начальника',
 'Первый заместитель руководителя',
 'Первый проректор',
 'Переводчик-дактилолог',
 'Плотник',
 'Повар',
 'Помощник воспитателя',
 'Помощник механика',
 'Помощник проректора',
 'Помощник режиссера',
 'Помощник ректора',
 'Президент',
 'Преподаватель',
 'Преподаватель-организатор основ безопасности жизнедеятельности',
 'Программист',
 'Профессор',
 'Психолог',
 'Рабочий по комплексному обслуживанию и ремонту зданий',
 'Редактор',
 'Режиссер',
 'Режиссер-постановщик',
 'Ректор',
 'Руководитель',
 'Руководитель контрактной службы',
 'Руководитель проектной группы',
 'Руководитель проектов',
 'Руководитель структурного подразделения',
 'Руководитель учебно-производственной практики',
 'Руководитель физического воспитания',
 'Сборщик изделий мебели из древесных материалов',
 'Секретарь руководителя',
 'Секретарь учебной части',
 'Системный администратор',
 'Слесарь по ремонту автомобилей',
 'Слесарь-ремонтник',
 'Слесарь-сантехник',
 'Советник',
 'Советник при ректорате',
 'Социальный педагог',
 'Специалист',
 'Специалист административно-хозяйственной деятельности',
 'Специалист по закупкам',
 'Специалист по защите информации',
 'Специалист по интернет-маркетингу',
 'Специалист по кадрам',
 'Специалист по охране труда',
 'Специалист по связям с общественностью',
 'Специалист по сетевому администрированию',
 'Специалист по технической документации в области информационных технологий',
 'Специалист по учебно-методической работе',
 'Специалист по экспозиционной и выставочной деятельности',
 'Старший администратор баз данных',
 'Старший вожатый',
 'Старший воспитатель',
 'Старший дежурный по режиму',
 'Старший инженер-сметчик',
 'Старший мастер',
 'Старший методист',
 'Старший механик',
 'Старший моторист',
 'Старший научный сотрудник',
 'Старший педагог дополнительного образования',
 'Старший педагог-психолог',
 'Старший преподаватель',
 'Старший программист',
 'Старший режиссер монтажа',
 'Старший специалист административно-хозяйственной деятельности',
 'Старший специалист по закупкам',
 'Старший специалист по кадрам',
 'Старший специалист по сетевому администрированию',
 'Старший тренер-преподаватель',
 'Старший экономист',
 'Сторож',
 'Сурдопедагог',
 'Техник',
 'Техник по эксплуатации зданий',
 'Техник-смотритель',
 'Техник-технолог',
 'Технический редактор',
 'Технолог',
 'Тренер-преподаватель',
 'Третий штурман',
 'Тьютор',
 'Уборщик служебных и производственных помещений',
 'Уборщик территории',
 'Учебный мастер',
 'Ученый секретарь',
 'Учитель',
 'Учитель-дефектолог',
 'Учитель-логопед',
 'Фотограф',
 'Хореограф',
 'Хормейстер',
 'Художественный руководитель',
 'Художник по свету',
 'Художник-конструктор (дизайнер)',
 'Художник-оформитель',
 'Художник-постановщик',
 'Чертежник',
 'Швея',
 'Экономист',
 'Экскурсовод',
 'Эксперт',
 'Электромеханик',
 'Юрисконсульт',
 'ведущий Аналитик',
 'ведущий Бухгалтер',
 'ведущий Документовед',
 'специалист по технической документации в области информационных технологий',
 'старший Администратор',
 'старший Аналитик',
 'старший Делопроизводитель']

In [16]:
jobs = ['Учитель-дефектолог', 'Тьютор', 'Педагог-психолог ', 'Учитель-логопед', 'Ассистент по оказанию технической помощи', 'Сурдопедагог', 'Тифлопедагог']

In [25]:
ans = res[res.job.isin(jobs)][['inn', 'job', 'stv']].groupby(['inn', 'job']).sum().unstack().fillna(0.0)

In [30]:
ans.index.names = ['inn']

In [34]:
ans.columns = [s[1] for s in ans.columns]

In [35]:
ans

,Ассистент по оказанию технической помощи,Педагог-психолог,Сурдопедагог,Тьютор,Учитель-дефектолог,Учитель-логопед
inn,,,,,,
5003021368,0.0,18.0,0.0,0.00,3.000,23.00
5003021495,3.5,33.7,0.0,61.00,15.675,32.97
5003021640,0.0,14.0,0.0,4.00,2.750,20.00
5003096290,1.0,4.0,0.0,23.30,2.000,2.00
5030032182,0.0,4.0,0.0,6.00,5.000,7.00
...,...,...,...,...,...,...
7743937357,0.0,4.0,0.0,2.00,0.000,1.00
7743939315,0.0,2.0,0.0,0.00,1.000,2.00
7743940590,0.0,6.0,0.0,4.00,2.000,5.00
9715206976,0.0,8.5,0.0,8.15,7.250,7.50
9715217689,0.0,6.0,0.0,0.00,4.200,5.00

In [38]:
otv = get_otv()

In [40]:
otv = otv.fillna(0)

In [42]:
otv['ekis'] = otv['ekis'].astype('int')

In [43]:
otv

,inn,okr,otv,sch_name,ekis
0,7743085543,САО,Рагимова Виктория Олеговна,ГБОУ Спецшкола № 1,13964
1,7713229928,САО,Горбанева Светлана Васильевна,ГКОУ КШИ № 1,13136
2,7704271031,ЦАО,Майильян Елена Александровна,ГБПОУ ПТ № 2,13277
3,7714093099,САО,Горбанева Светлана Васильевна,ГКОУ СКОШИ № 2,13139
4,7709438340,ЦАО,Майильян Елена Александровна,ГБПОУ КСУ № 3,11681
...,...,...,...,...,...
935,7728113806,0,0,ИКИ РАН,0
936,7728013512,0,0,ИПУ РАН,0
937,7717067481,0,0,ГБОУ ШОР № 1,0
938,7729133548,0,0,СУНЦ МГУ,0
939,7734121555,0,0,ФГАУ «УИСП» Минобороны России,0

In [46]:
ans = pd.merge(ans, otv[['inn', 'sch_name', 'ekis']], how='left', on='inn')

In [47]:
print_df(ans, 'Ставки овз по орг-ям')