In [1]:
from openpyxl import Workbook, load_workbook
import pandas as pd
from openpyxl.utils.dataframe import dataframe_to_rows as df_to_row
import numpy as np

In [2]:
from szp_funcs import path_to_data, print_df, to_double, load_month, day_types

In [7]:
months = ['apr']
inn = 7736110982
jobs = ['Воспитатель', 'Учитель']

In [5]:
res = load_month(months[0])

In [12]:
search = res[(res.inn == inn) & (res[months[0] + '_job'].isin(jobs)) & (res[months[0] + '_type'] == day_types[0])]

In [13]:
search

,inn,snils,apr_sum,apr_job,apr_day,apr_type,apr_stv,apr_status,apr_status_pref,apr_wday,apr_nday
172084,7736110982,001-192-067 85,94951.92,Учитель,0.0,Основное место работы,1.44,Работа,Работа,20.0,21.0
172085,7736110982,001-192-122 75,101225.29,Учитель,0.0,Основное место работы,1.78,Работа,Болезнь,17.0,21.0
172093,7736110982,001-360-756 92,160144.27,Учитель,1.0,Основное место работы,1.67,Работа,Работа,21.0,21.0
172098,7736110982,001-458-969 35,116408.33,Учитель,0.0,Основное место работы,1.28,Работа,Работа,20.0,21.0
172158,7736110982,001-731-434 90,115289.11,Учитель,1.0,Основное место работы,1.33,Работа,Работа,21.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...
173753,7736110982,189-198-323 33,147372.00,Учитель,1.0,Основное место работы,1.72,Работа,Работа,21.0,21.0
173766,7736110982,191-009-805 52,53189.62,Учитель,0.0,Основное место работы,0.67,Отпуск учебный оплачиваемый,Работа,16.0,21.0
173775,7736110982,193-132-196 57,54014.13,Воспитатель,0.0,Основное место работы,1.00,Работа,Работа,16.0,21.0
173784,7736110982,194-726-782 22,93517.78,Учитель,0.0,Основное место работы,1.32,Болезнь,Работа,17.0,21.0
173808,7736110982,203-797-890 95,126955.20,Учитель,1.0,Основное место работы,1.78,Работа,Работа,21.0,21.0

In [15]:
search[['snils', months[0] + '_job']].groupby(months[0] + '_job').nunique()

             snils
apr_job
Воспитатель     22
Учитель        132

Дальше личная обработка для заведения по сзп и т.д.

In [12]:
months = ['jan', 'feb', 'mar', 'apr']
inn = 7736110982

In [61]:
from szp_funcs import custom_create_res, load_groups, szp, gku_inn, sum_fot

In [5]:
ped, isp, aup = load_groups('input')

In [6]:
all = custom_create_res(months, load_month)
mon = load_month(months[-1])

In [7]:
all

,inn,snils,sum_jan,job_jan,day_jan,type_jan,stv_jan,status_jan,status_pref_jan,sum_feb,...,status_pref_mar,sum_apr,job_apr,day_apr,type_apr,stv_apr,status_apr,status_pref_apr,wday_apr,nday_apr
0,5003021368,001-171-362 75,51468.76,Помощник воспитателя,0.0,Основное место работы,1.0,Работа,Работа,41289.47,...,Работа,58500.00,Помощник воспитателя,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
1,5003021368,001-191-281 85,106626.88,Учитель,1.0,Основное место работы,1.0,Работа,Работа,139753.92,...,Работа,105890.88,Учитель,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
2,5003021368,001-244-107 65,109394.87,Учитель,1.0,Основное место работы,1.0,Работа,Работа,109541.13,...,Работа,98522.15,Учитель,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
3,5003021368,001-263-234 77,74520.00,Воспитатель,1.0,Основное место работы,1.0,Работа,Работа,81178.00,...,Работа,77794.00,Воспитатель,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
4,5003021368,001-322-594 80,83013.52,Специалист,1.0,Основное место работы,1.0,Работа,Работа,75815.00,...,Работа,75815.00,Специалист,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175916,9718071371,143-168-262 49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,107526.00,Бухгалтер,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
175917,9718071371,145-089-428 75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,48035.62,Бухгалтер,1.0,Основное место работы,1.0,Работа,NaN,13.0,13.0
175918,9718071371,145-624-332 54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,299871.00,Начальник отдела,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0
175919,9718071371,158-325-680 86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,60000.00,Учитель,0.0,Основное место работы,1.0,Работа,Работа,NaN,NaN
175920,9718071371,198-317-420 02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,77596.00,Бухгалтер,1.0,Основное место работы,1.0,Работа,Работа,21.0,21.0

In [10]:
all['szp'] = all.apply(lambda row: szp(row, months), axis=1)

In [15]:
all = all[(all.inn == inn) & (all['type_' + months[-1]] == day_types[0])]
mon = mon[(mon.inn == inn) & (mon['type_' + months[-1]] == day_types[0])]

In [22]:
mon['stv_' + months[-1]].fillna(1, inplace=True)
mon['nday_' + months[-1]].fillna(1, inplace=True)
mon['wday_' + months[-1]].fillna(mon['nday_' + months[-1]], inplace=True)

C:\Users\PetukhovMD\AppData\Local\Temp\ipykernel_11812\500355228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mon['stv_' + months[-1]].fillna(1, inplace=True)
C:\Users\PetukhovMD\AppData\Local\Temp\ipykernel_11812\500355228.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mon['nday_' + months[-1]].fillna(1, inplace=True)
C:\Users\PetukhovMD\AppData\Local\Temp\ipykernel_11812\500355228.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mon['wday_' + months[-1]].fillna(mon['nday_' + months[-1]], inplace=True)

In [23]:
mon['spis'] = mon['stv_' + months[-1]] * mon['wday_' + months[-1]] / mon['nday_' + months[-1]]

C:\Users\PetukhovMD\AppData\Local\Temp\ipykernel_11812\1230406279.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mon['spis'] = mon['stv_' + months[-1]] * mon['wday_' + months[-1]] / mon['nday_' + months[-1]]

In [25]:
mon[mon['job_' + months[-1]].isin(aup)]['spis'].sum()

24.922760572760573

In [26]:
mon[mon['job_' + months[-1]].isin(ped)]['spis'].sum()

757.0009976023975

In [27]:
mon['spis'].sum()

1704.3664928527614

In [28]:
mon['snils'].nunique()

1372

In [30]:
all

,inn,snils,sum_jan,job_jan,day_jan,type_jan,stv_jan,status_jan,status_pref_jan,sum_feb,...,sum_apr,job_apr,day_apr,type_apr,stv_apr,status_apr,status_pref_apr,wday_apr,nday_apr,szp
154861,7736110982,001-123-880 75,116484.38,Концертмейстер,1.0,Основное место работы,1.88,Работа,Работа,111419.84,...,120186.52,Концертмейстер,0.0,Основное место работы,1.88,Работа,Работа,25.0,26.0,121521.2575
154862,7736110982,001-123-903 65,112536.22,Педагог дополнительного образования,1.0,Основное место работы,1.89,Работа,Работа,108983.22,...,114966.07,Педагог дополнительного образования,0.0,Основное место работы,1.89,Работа,Работа,24.0,26.0,111448.5600
154863,7736110982,001-183-119 79,54859.47,Педагог-организатор,0.0,Основное место работы,1.00,Работа,Работа,53355.08,...,30535.71,Педагог-организатор,0.0,Основное место работы,1.00,Работа,Отпуск учебный оплачиваемый,10.0,21.0,45855.3825
154864,7736110982,001-192-067 85,104190.17,Учитель,0.0,Основное место работы,1.44,Работа,Работа,30679.90,...,94951.92,Учитель,0.0,Основное место работы,1.44,Работа,Работа,20.0,21.0,80397.8975
154865,7736110982,001-192-122 75,75102.22,Учитель,0.0,Основное место работы,1.78,Работа,Работа,64007.43,...,101225.29,Учитель,0.0,Основное место работы,1.78,Работа,Болезнь,17.0,21.0,62583.7350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175825,7736110982,138-236-003 42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66880.00,Методист,1.0,Основное место работы,0.95,Работа в отпуске по уходу за ребенком,Отпуск по беременности и родам,16.0,16.0,66880.0000
175826,7736110982,143-959-917 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43312.50,Педагог-организатор,1.0,Основное место работы,1.00,Работа,NaN,15.0,15.0,43312.5000
175827,7736110982,165-511-213 41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59285.71,Учитель,1.0,Основное место работы,1.00,Работа,NaN,10.0,10.0,59285.7100
175828,7736110982,173-836-457 00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97505.63,Ведущий специалист,1.0,Основное место работы,0.95,Работа в отпуске по уходу за ребенком,Работа в отпуске по уходу за ребенком,21.0,21.0,97505.6300
175829,7736110982,195-211-458 66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500.00,Уборщик территории,1.0,Основное место работы,1.00,Работа,NaN,1.0,1.0,1500.0000

In [43]:
def for_szp(row, months):
    b = True
    for i in months:
        if pd.isna(row['stv_' + i]) :
            continue
        b = b & (row['day_' + i] == 1) & (row['stv_' + i] >= 1)
    return b

In [44]:
all['for_szp'] = all.apply(lambda row: for_szp(row, months), axis=1)

C:\Users\PetukhovMD\AppData\Local\Temp\ipykernel_11812\3108571858.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all['for_szp'] = all.apply(lambda row: for_szp(row, months), axis=1)

In [47]:
all[all['job_' + months[-1]].isin(aup)]

,inn,snils,sum_jan,job_jan,day_jan,type_jan,stv_jan,status_jan,status_pref_jan,sum_feb,...,job_apr,day_apr,type_apr,stv_apr,status_apr,status_pref_apr,wday_apr,nday_apr,szp,for_szp
154879,7736110982,001-508-752 01,163098.34,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,162130.50,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,16.0,21.0,159915.5575,False
154893,7736110982,001-603-086 77,125139.87,Руководитель,1.0,Основное место работы,0.350,Работа,Работа,34515.00,...,Руководитель,0.0,Основное место работы,0.35,Болезнь,Работа,17.0,21.0,80619.0525,False
154997,7736110982,005-376-472 39,162162.00,Начальник,1.0,Основное место работы,1.000,Работа,Работа,162162.00,...,Начальник,0.0,Основное место работы,1.00,Работа,Отпуск основной,15.0,21.0,148258.6675,False
155104,7736110982,017-288-398 75,203129.98,Руководитель,0.0,Основное место работы,1.000,Работа,Работа,244967.00,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,29.0,21.0,259302.4650,False
155121,7736110982,019-060-171 18,121259.72,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,120466.62,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,11.0,21.0,119152.7650,False
155166,7736110982,019-482-943 80,238320.00,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,238320.00,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,267534.0000,True
155174,7736110982,019-712-185 49,218820.58,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,183713.00,...,Руководитель,0.0,Основное место работы,1.00,Работа,Отпуск основной,18.0,22.0,188213.3825,False
155189,7736110982,020-066-034 80,125870.86,Руководитель,0.0,Основное место работы,1.000,Работа,Работа,169841.70,...,Руководитель,0.0,Основное место работы,1.00,Работа,Отпуск основной,15.0,21.0,145718.7700,False
155249,7736110982,024-019-133 97,145868.00,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,84268.71,...,Руководитель,0.0,Основное место работы,1.00,NaN,Работа,15.0,21.0,136166.7600,False
155287,7736110982,026-937-717 84,180684.00,Заместитель руководителя,1.0,Основное место работы,1.000,Работа,Работа,183540.00,...,Заместитель руководителя,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,213032.2500,True
155302,7736110982,030-052-211 66,434098.00,Директор,1.0,Основное место работы,1.000,Работа,Работа,228472.63,...,Директор,0.0,Основное место работы,1.00,Работа,Работа,13.0,21.0,379038.0300,False
155340,7736110982,038-743-176 76,147420.00,Начальник,1.0,Основное место работы,1.000,Работа,Работа,155610.00,...,Начальник,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,153562.5000,True
155413,7736110982,051-167-489 47,158911.60,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,143171.31,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,148673.3375,False
155472,7736110982,063-129-749 58,382006.00,Заместитель директора,1.0,Основное место работы,1.000,Работа,Работа,382006.00,...,Заместитель директора,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,382006.0000,True
155562,7736110982,080-262-909 49,171716.58,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,127063.67,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,17.0,21.0,160577.4225,False
155586,7736110982,102-095-820 15,159323.56,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,98975.25,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,18.0,20.0,131781.5600,False
155611,7736110982,108-732-641 56,179361.00,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,178973.38,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,16.0,21.0,189323.5000,False
155617,7736110982,110-142-363 75,173238.98,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,172324.69,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,14.0,21.0,170400.8400,False
155624,7736110982,112-330-283 89,154470.00,Советник,1.0,Основное место работы,1.000,Работа,Работа,154980.00,...,Заместитель руководителя,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,154852.5000,True
155668,7736110982,120-764-223 25,382006.00,Заместитель директора,1.0,Основное место работы,1.000,Работа,Работа,382006.00,...,Заместитель директора,0.0,Основное место работы,1.00,Работа,Работа,20.0,21.0,379020.2775,False
155706,7736110982,124-573-307 45,155610.00,Начальник,1.0,Основное место работы,1.000,Работа,Работа,155610.00,...,Начальник,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,155610.0000,True
155736,7736110982,128-371-965 81,382006.00,Заместитель директора,1.0,Основное место работы,1.000,Работа,Работа,382006.00,...,Заместитель директора,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,382006.0000,True
155741,7736110982,128-609-476 84,177834.15,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,220271.09,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,229845.7200,False
155794,7736110982,134-232-636 25,277931.34,Руководитель,0.0,Основное место работы,1.000,Работа,Работа,271381.99,...,Руководитель,0.0,Основное место работы,1.00,Работа,Работа,19.0,26.0,278613.2550,False
155879,7736110982,141-877-233 73,80825.58,Руководитель,0.0,Основное место работы,0.875,Работа в отпуске по уходу за ребенком,Работа в отпуске по уходу за ребенком,138159.02,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,18.0,18.0,130214.6500,False
155881,7736110982,142-039-468 37,382006.00,Первый заместитель директора,1.0,Основное место работы,1.000,Работа,Работа,382006.00,...,Первый заместитель директора,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,382006.0000,True
155957,7736110982,149-694-453 24,197636.76,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,144265.59,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,22.0,21.0,164046.6200,False
155970,7736110982,150-965-541 76,207207.00,Руководитель,1.0,Основное место работы,1.000,Работа,Работа,207207.00,...,Руководитель,1.0,Основное место работы,1.00,Работа,Работа,21.0,21.0,207207.0000,True
156060,7736110982,162-352-596 60,154980.00,Заместитель руководителя,1.0,Основное место работы,1.000,Работа,Работа,154980.00,...,Заместитель руководителя,0.0,Основное место работы,1.00,Работа,Работа,11.0,21.0,136530.0000,False

In [46]:
all[all.for_szp == True]['szp'].mean()

96851.85167174797

In [57]:
all['szp'].mean()

89280.67360726434

In [53]:
all[all.job_apr.isin(['Первый заместитель директора', 'Заместитель директора'])]['szp'].mean()

381259.569375

In [58]:
all[all.job_apr == 'Директор']['szp'].mean()

379038.02999999997

In [55]:
all[(all.job_apr.isin(ped)) & (all.for_szp == True)]['szp'].mean()

105093.27682926829

In [59]:
all[(all.job_apr.isin(ped)) ]['szp'].mean()

89635.89124263039

In [56]:
all[(all.job_apr.isin(aup) == False) & (all.job_apr.isin(ped) == False) & (all.for_szp == True)]['szp'].mean()

85644.50727517986

In [60]:
all[(all.job_apr.isin(aup) == False) & (all.job_apr.isin(ped) == False) ]['szp'].mean()

83186.63691337718

In [62]:
mon['fot'] = mon.apply(lambda row: sum_fot(row, months[-1:]), axis=1)

C:\Users\PetukhovMD\AppData\Local\Temp\ipykernel_11812\3600343977.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mon['fot'] = mon.apply(lambda row: sum_fot(row, months[-1:]), axis=1)

In [64]:
ans = mon.groupby('job_' + months[-1])[['job_' + months[-1], 'stv_' + months[-1]]].sum().reset_index()

In [70]:
ans = pd.merge(ans, mon.groupby('job_' + months[-1])[['snils']].nunique().reset_index(), how='left')

In [73]:
ans = pd.merge(ans,mon.groupby('job_' + months[-1])[['sum_' + months[-1]]].mean().reset_index(), how='left')

In [76]:
ans = pd.merge(ans, mon.groupby('job_' + months[-1])['fot'].sum().reset_index(), how='left')

In [78]:
print_df(ans, 'По вг данные по должностям')